# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title: Bootstrap
description: The most popular HTML, CSS, and JS framework in the world.
twitter: sea_local
authors: Mark Otto, Jacob Thornton, and Bootstrap contributors
social_logo_path: /assets/brand/bootstrap-social-logo.png
social_image_path: /assets/brand/bootstrap-social.png

# Custom vars
current_version:  4.0.0-alpha.6
repo:             https://github.com/sealocal/bootstrap
slack:            https://bootstrap-slack.herokuapp.com

download:
  source:         https://github.com/sealocal/bootstrap/archive/v4.0.0-alpha.6.zip
  dist:           https://github.com/sealocal/bootstrap/releases/download/v4.0.0-alpha.6/bootstrap-4.0.0-alpha.6-dist.zip

